name: Ada (GNAT)

on:
  push:
    branches: [ "dev*" ]
  pull_request:
    branches: [ "dev*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild

    - name: Build Tools
      run: gprbuild -j0 -p build/gnat/tools.gpr
      
    - name: Generate SDL.Events.Keyboards 
      run: ./build/gnat/gen/debug/tools/gen_keyboard >build/gnat/gen/src/sdl-events-keyboards.ads

    - name: Build SDL2 Main, Image, TTF
      run: gprbuild -j0 -p build/gnat/sdlada.gpr

    - name: Build Test
      run: gprbuild -j0 -p build/gnat/test.gpr
